openapi: 3.0.1
info:
  description: A placeholder API that allows OpenAPI tools to be used to generate
    code for a companion specification.
  title: opcfoundation.org:2024_10:starterkit:measurements
  version: 1.00.0
servers:
- url: http://localhost:4840
paths:
  /get:
    get:
      operationId: Get
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
          description: ModelDataTypes
components:
  schemas:
    OrientationDataType:
      example:
        X: 0.8008281904610115
        "Y": 6.027456183070403
        ProfileName: ProfileName
        Rotation: 1.4658129805029452
      properties:
        ProfileName:
          type: string
        X:
          format: double
          type: number
        "Y":
          format: double
          type: number
        Rotation:
          format: double
          type: number
      type: object
    Response:
      example:
        OrientationDataType:
          X: 0.8008281904610115
          "Y": 6.027456183070403
          ProfileName: ProfileName
          Rotation: 1.4658129805029452
      properties:
        OrientationDataType:
          $ref: '#/components/schemas/OrientationDataType'
      title: Response

